const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSongs: (search, filters, sortBy, sortDir) => ipcRenderer.invoke('db:getSongs', search, filters, sortBy, sortDir),
  getSong: (id) => ipcRenderer.invoke('db:getSong', id),
  updateSong: (id, fields) => ipcRenderer.invoke('db:updateSong', id, fields),
  deleteSong: (id) => ipcRenderer.invoke('db:deleteSong', id),
  getDistinctValues: (field) => ipcRenderer.invoke('db:getDistinctValues', field),
  getQueue: () => ipcRenderer.invoke('db:getQueue'),
  addToQueue: (songId) => ipcRenderer.invoke('db:addToQueue', songId),
  removeFromQueue: (queueId) => ipcRenderer.invoke('db:removeFromQueue', queueId),
  clearQueue: () => ipcRenderer.invoke('db:clearQueue'),
  reorderQueue: (queueId, newPos) => ipcRenderer.invoke('db:reorderQueue', queueId, newPos),
  getLists: () => ipcRenderer.invoke('db:getLists'),
  saveLists: (languages, genres) => ipcRenderer.invoke('db:saveLists', languages, genres),
  incrementPlayCount: (id) => ipcRenderer.invoke('db:incrementPlayCount', id),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (s) => ipcRenderer.invoke('settings:save', s),
  chooseSongsFolder: () => ipcRenderer.invoke('settings:chooseFolder'),
  setVolume: (vol) => ipcRenderer.invoke('settings:setVolume', vol),
  getFilePath: (song) => ipcRenderer.invoke('player:getFilePath', song),
  getNextInQueue: () => ipcRenderer.invoke('player:getNextInQueue'),
  ytSearch: (query) => ipcRenderer.invoke('yt:search', query),
  fetchYtInfo: (url) => ipcRenderer.invoke('yt:fetchInfo', url),
  downloadSong: (opts) => ipcRenderer.invoke('yt:download', opts),
  onDownloadProgress: (cb) => ipcRenderer.on('download:progress', (_, data) => cb(data)),
  onDownloadDone: (cb) => ipcRenderer.on('download:done', (_, data) => cb(data)),
  onDownloadError: (cb) => ipcRenderer.on('download:error', (_, data) => cb(data)),
  removeAllListeners: (ch) => ipcRenderer.removeAllListeners(ch),
});
